# Generated by Django 5.1.6 on 2025-02-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pacer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
