# Generated by Django 5.1.6 on 2025-02-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
    ]
