# Generated by Django 5.1.6 on 2025-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_remove_category_pacer_category_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='director',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, to='movie_app.hastag'),
        ),
    ]
