# Generated by Django 5.1.6 on 2025-02-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_hastag_director_hash_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
    ]
